---
title: "Resampling_test"
output: html_document
---

```{r preliminaries, message=FALSE, echo=FALSE}
# Constants
OUTPUT_DIR		<- "outputs/"
DATA_DIR <- 'data'
# Create output and log folders if they do not exist
if(!file.exists(OUTPUT_DIR)) dir.create(OUTPUT_DIR)

library(kableExtra)
# Load required packages
library(data.table)
library(lubridate)
library(knitr)
library(ggpubr)

library(ggplot2)
theme_set(theme_bw())
library(cowplot)
library(ggmap)
library(maps)
library(mapdata)
# install.packages("ggExtra")
library(ggExtra)

library(tidyr)
library(hexbin)
library(dplyr)

# install.packages('ggbeeswarm')
library(ggbeeswarm)

# Source all needed functions
source('functions.R')

# Set chunks defaults; these options will be applied to all subsequent chunks
knitr::opts_chunk$set(results = 'hide', message = TRUE, include = TRUE, 
                      echo = FALSE, warning = FALSE,
                      fig.height = 4, fig.width = 8, cache = FALSE)
```


## load data
```{r load data}
# input data
read_file <- function(x) read.csv(file.path(DATA_DIR, x), stringsAsFactors = FALSE)

GPP <- read_file('GlobalGPP_Sum.csv') # GPP estimates from published paper
GPP %>% filter(Pub_year > 1980 & Flag != "Model") -> GPP

GlobalRs <- read_file('GlobalRs.csv') # estimates of global Rs
GlobalRs %>% filter(Pub_year > 1980) -> GlobalRs
# (Ra/GPP) Piao, Shilong, et al. "Forest annual carbon cost: A global‐scale analysis of autotrophic respiration." Ecology 91.3 (2010): 652-661.
```


## Reasmple RSG and GPP
* Method 1 - ignore SD and resample from `r nrow (GlobalRs)` or `r nrow (GPP)` with replacement
* Method 2 - using SD, but calculated based on mean and covariance
* Method 3 - using SD, but using the maximum if missing

```{r}
set.seed(20191111)
N_SAMPLES = 50000
# resample global soil respiration (RSG)
resample_RSG <- tibble(RSG1_no_SD = sample(GlobalRs$Rs, N_SAMPLES, replace = TRUE),
                       RSG2_cal_SD = replace_calSD_and_generate(GlobalRs$Rs, GlobalRs$SD),
                       RSG3_max_SD = replace_maxSD_and_generate(GlobalRs$Rs, GlobalRs$SD)
                       )

# resample gross primary production (GPP)
resample_GPP <- tibble(GPP1_no_SD = sample(GPP$GPP, N_SAMPLES, replace = TRUE),
                       GPP2_cal_SD = replace_calSD_and_generate(GPP$GPP, GPP$SD),
                       GPP3_max_SD = replace_maxSD_and_generate(GPP$GPP, GPP$SD)
                       )
```


## Compare the results of different re-sampling methods
```{r}
# comparing RSG resample results
resample_RSG %>%
  gather(Rs_resample_type) %>% 
  ggplot(aes(value, fill = Rs_resample_type)) +
  theme_cowplot() +
  geom_density(stat = 'density', alpha = 0.5) +
  #  theme(legend.position = c(0.75, 0.75)) +
  coord_cartesian(xlim = c(0, 140)) +
  # reverse the color scale so that teal (color 1) is always observations, 
  # while pink is always implied fluxes
  scale_fill_discrete("", h.start = 180) + scale_color_discrete(h.start = 180) +
  ylab("Density") +
  xlab(expression(R[S]~(Pg~C~yr^{-1}))) 

# comparing GPP resample results
resample_GPP %>%
  gather(GPP_resample_type) %>% 
  ggplot(aes(value, fill = GPP_resample_type)) +
  theme_cowplot() +
  geom_density(stat = 'density', alpha = 0.5) +
  #  theme(legend.position = c(0.75, 0.75)) +
  coord_cartesian(xlim = c(0, 250)) +
  # reverse the color scale so that teal (color 1) is always observations, 
  # while pink is always implied fluxes
  scale_fill_discrete("", h.start = 180) + scale_color_discrete(h.start = 180) +
  ylab("Density") +
  xlab(expression(R[S]~(Pg~C~yr^{-1}))) 
```


```{r}
# double peek issue - we lack RSG estimates between 80 and 90 Pg
# I added one more RSG estimate by using Konings (2019)'s Rh estimates and Tang (2020)'s Ra estimates, see csv url links 
# but it does not help a lot
GlobalRs %>% ggplot(aes(x = Pub_year, y = Rs)) + geom_point()
```

